version: 0.2

phases:
  install:
    commands:
      - echo "No dependencies to install"

  build:
    commands:
      - echo "No build step required for static HTML"

artifacts:
  files:
    - index.html
